"""
GenWealth Advisor Engine — Phase 3, Step 3.3
============================================
Module: src/advisor/guardrails.py

Safety & Compliance Layer for AI-generated financial reports.

Design Philosophy (per architectural review):
  • Detection is SEPARATE from replacement.
    Regex identifies banned phrases and raises flags — it does NOT attempt
    mid-sentence rewrites, which risk corrupting grammatical flow of the
    synthesized Gemini report.
  • Flags are surfaced in the function's return metadata so downstream
    callers (e.g. LLMAdvisorEngine) can log, escalate, or gate the response.
  • The regulatory disclaimer is appended as a clean, self-contained block
    that never intersects with the report body.

Compliance Context:
  • India (NSE/BSE): SEBI (Securities and Exchange Board of India)
    Circular SEBI/HO/MIRSD/MIRSD_SECFATF/P/CIR/2023 — Research Analyst Regs.
  • US (NYSE/NASDAQ): SEC Regulation Best Interest (Reg BI) and FINRA Rule 2111.
  • The disclaimer covers both jurisdictions for universal deployment.
"""

# ---------------------------------------------------------------------------
# Standard Library
# ---------------------------------------------------------------------------
import logging
import re
from typing import Optional

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  [%(levelname)-8s]  %(name)s — %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("genwealth.guardrails")

# ---------------------------------------------------------------------------
# Banned Phrase Registry
# ---------------------------------------------------------------------------
# Each entry is a compiled regex pattern. Patterns use word boundaries to
# avoid false positives (e.g. "safe" inside "safe harbour" should not trigger).
#
# Design: detection-only. Do NOT replace mid-sentence — flag only.
_BANNED_PATTERNS: list[tuple[re.Pattern, str]] = [
    # Absolute return guarantees
    (re.compile(r"\bguaranteed?\s+returns?\b",          re.IGNORECASE),
     "Contains absolute return guarantee language ('guaranteed return')"),
    (re.compile(r"\bguaranteed?\s+profit\b",            re.IGNORECASE),
     "Contains absolute profit guarantee ('guaranteed profit')"),

    # Risk-free / zero-risk claims
    (re.compile(r"\b100\s*%\s+safe\b",                  re.IGNORECASE),
     "Contains absolute safety claim ('100% safe')"),
    (re.compile(r"\brisk[\s-]?free\s+invest\w*\b",      re.IGNORECASE),
     "Contains risk-free investment claim"),
    (re.compile(r"\bzero[\s-]risk\b",                   re.IGNORECASE),
     "Contains zero-risk claim"),
    (re.compile(r"\bno[\s-]risk\b",                     re.IGNORECASE),
     "Contains no-risk claim"),

    # Certain/definitive profit predictions
    (re.compile(r"\bwill\s+definitely\s+(rise|gain|profit|grow|increase)\b",
                re.IGNORECASE),
     "Contains definitive price prediction language"),
    (re.compile(r"\bcertain(ly)?\s+profit\b",            re.IGNORECASE),
     "Contains certainty-of-profit claim"),
    (re.compile(r"\bimpossible\s+to\s+lose\b",           re.IGNORECASE),
     "Contains 'impossible to lose' language"),

    # Unlicensed solicitation phrases
    (re.compile(r"\byou\s+must\s+(buy|sell|invest\s+now)\b",
                re.IGNORECASE),
     "Contains directive investment instruction without regulatory cover"),
    (re.compile(r"\bact\s+now\s+(before|or)\b",          re.IGNORECASE),
     "Contains high-pressure urgency solicitation language"),

    # Insider / non-public information implications
    (re.compile(r"\binsider\s+(tip|information|knowledge)\b",
                re.IGNORECASE),
     "Contains reference to insider information — potential regulatory violation"),
]

# ---------------------------------------------------------------------------
# Regulatory Disclaimer
# ---------------------------------------------------------------------------
_DISCLAIMER: str = """
---

## ⚠️ Regulatory Disclaimer & Risk Disclosure

**GenWealth AI — Investment Research Disclosure**

This report has been generated by an artificial intelligence system (GenWealth AI)
and is provided for **informational and educational purposes only**. It does **not**
constitute personalised investment advice, a solicitation to buy or sell any security,
or a guarantee of any financial outcome.

**Key Disclosures:**

1. **Not Financial Advice**: This output is generated by an automated AI system and
   has not been reviewed or endorsed by a licensed financial advisor, SEBI-registered
   Research Analyst, or SEC-registered Investment Adviser.

2. **No Guarantee of Returns**: All investment strategies involve risk. Past performance
   of any model, strategy, or backtest result is **not indicative of future results**.
   Market conditions can change rapidly and unpredictably.

3. **AI Limitations**: The AI model may produce inaccurate, incomplete, or outdated
   information. Always verify critical figures against primary data sources before
   making any investment decision.

4. **Jurisdiction Notice**:
   - *India*: This output is not registered research under SEBI (Research Analysts)
     Regulations, 2014. Consult a SEBI-registered advisor for regulated advice.
   - *United States*: This output does not constitute advice under SEC Regulation Best
     Interest (Reg BI) or FINRA Rule 2111. Consult a registered investment adviser.

5. **No Liability**: GenWealth AI and its developers accept no liability for losses
   incurred from decisions made based on this report.

*Invest responsibly. Diversify. Consult a qualified financial professional.*
"""


# ===========================================================================
# 1. Core Sanitization Function
# ===========================================================================

def sanitize_and_append_disclaimer(
    response_text: str,
    strict_mode: bool = False,
) -> str:
    """
    Detect compliance violations in an AI-generated report and append a
    regulatory disclaimer.

    **Sanitization Strategy** (detection-first, non-destructive):
        1. Scan the report text against all ``_BANNED_PATTERNS`` using
           regex pattern matching.
        2. For each match, log a compliance warning and record the flag.
        3. If any banned phrase is detected AND ``strict_mode=True``,
           a prominent ⚠️ compliance notice is prepended to the report
           body (non-destructive — the original text is preserved so
           the reader can exercise their own judgment).
        4. The standardised ``_DISCLAIMER`` block is **always** appended
           at the end of the report, regardless of violation status.

    Design note on why phrases are NOT replaced mid-sentence:
        Automated mid-sentence substitutions (e.g., swapping "guaranteed
        return" → "potential return") frequently corrupt the grammatical
        structure of multi-paragraph LLM outputs and may produce nonsensical
        financial statements. Detection + flagging is legally safer and
        operationally cleaner.

    Args:
        response_text (str): The AI-generated financial report text.
        strict_mode   (bool): If True, prepend a compliance warning block
                              when violations are detected. Default False.

    Returns:
        str: The sanitised report with the regulatory disclaimer appended.
             In ``strict_mode``, a compliance alert header is prepended
             if any banned phrases were detected.

    Example:
        >>> raw = "This is a guaranteed return strategy with zero risk."
        >>> safe = sanitize_and_append_disclaimer(raw, strict_mode=True)
        >>> "⚠️ COMPLIANCE" in safe
        True
        >>> "Regulatory Disclaimer" in safe
        True
    """
    if not response_text or not response_text.strip():
        logger.warning("guardrails received empty report text; appending disclaimer only.")
        return _DISCLAIMER.strip()

    flags: list[str] = []

    # -- Step 1: Scan for banned patterns ------------------------------------
    for pattern, description in _BANNED_PATTERNS:
        matches = pattern.findall(response_text)
        if matches:
            flag_detail = (
                f"{description} — matched: {[m if isinstance(m, str) else ' '.join(m) for m in matches[:3]]}"
            )
            flags.append(flag_detail)
            logger.warning(
                "COMPLIANCE VIOLATION DETECTED: %s", flag_detail
            )

    if not flags:
        logger.info(
            "Guardrails: No compliance violations detected. "
            "Appending standard disclaimer."
        )
    else:
        logger.warning(
            "Guardrails: %d compliance flag(s) detected. "
            "Report flagged — disclaimer appended.",
            len(flags),
        )

    # -- Step 2: Build compliance header (strict mode only) ------------------
    compliance_header: str = ""
    if flags and strict_mode:
        flags_formatted = "\n".join(f"  - {f}" for f in flags)
        compliance_header = (
            "---\n"
            "## ⚠️ COMPLIANCE ALERT — Automated Review Flag\n\n"
            "The following potentially non-compliant phrases were detected "
            "in this AI-generated report. The report text has been preserved "
            "verbatim; exercise caution when interpreting flagged statements.\n\n"
            "**Detected Issues:**\n"
            f"{flags_formatted}\n\n"
            "---\n\n"
        )

    # -- Step 3: Assemble final output ---------------------------------------
    # Structure: [optional compliance header] + [report body] + [disclaimer]
    final_output = compliance_header + response_text.rstrip() + "\n" + _DISCLAIMER

    return final_output


# ===========================================================================
# 2. Standalone Flag Inspector (utility for callers)
# ===========================================================================

def get_compliance_flags(response_text: str) -> list[str]:
    """
    Scan report text and return compliance flags without modifying output.

    Lightweight helper for callers that need to check compliance status
    independently of the full sanitize pipeline (e.g., for logging or
    dashboard display).

    Args:
        response_text (str): The AI-generated report text to scan.

    Returns:
        list[str]: List of compliance flag descriptions. Empty list means
                   no violations detected.

    Example:
        >>> flags = get_compliance_flags("100% safe guaranteed return strategy")
        >>> len(flags)
        2
    """
    flags: list[str] = []
    for pattern, description in _BANNED_PATTERNS:
        if pattern.search(response_text):
            flags.append(description)
    return flags


# ===========================================================================
# 3. Self-Test Execution Block
# ===========================================================================

if __name__ == "__main__":
    """
    Self-test suite for guardrails.py.

    Run from project root:
        python -m src.advisor.guardrails

    Tests performed:
        1. Clean report — no violations expected
        2. Contaminated report — multiple violations expected
        3. Strict mode output inspection
        4. Disclaimer presence validation
        5. Edge case: empty input
    """
    import sys

    # Windows consoles default to cp1252 which cannot render em-dashes (—) or
    # emoji (⚠️) present in the SEBI/SEC disclaimer. Reconfigure stdout to
    # UTF-8 before any output is written.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    print("\n" + "=" * 70)
    print("  GenWealth — Phase 3 | guardrails.py Self-Test")
    print("=" * 70 + "\n")

    CLEAN_REPORT = """
## 1. Signal Interpretation
NVDA shows a bullish signal (0.78) supported by positive FinBERT sentiment (+0.42).
The 20/200 volatility ratio of 1.12 indicates moderate momentum expansion.

## 2. Portfolio Allocation Justification
The PPO agent's 23.75% allocation to NVDA is supported by the Sharpe ratio of 0.97,
which is above the equal-weight benchmark allocation threshold.

## 3. Risk Flags
Max drawdown of 18.5% remains elevated; position sizing should reflect this.

## 4. Actionable Stance
**BUY** — Evidence supports accumulation at current levels with a stop at -12%.
"""

    CONTAMINATED_REPORT = """
## Advisory
This strategy offers guaranteed returns of 35% per annum.
Invest now — this is a 100% safe, risk-free investment.
Our insider tips have never been wrong. Act now before the market opens!
You must buy NVDA immediately for certain profits.
"""

    # -- Test 1: Clean report -------------------------------------------------
    print("[TEST 1] Clean Report (no violations expected)...")
    flags_clean = get_compliance_flags(CLEAN_REPORT)
    if not flags_clean:
        print(f"  PASS  Zero compliance flags detected.\n")
    else:
        print(f"  WARN  Unexpected flags: {flags_clean}\n")

    # -- Test 2: Contaminated report ------------------------------------------
    print("[TEST 2] Contaminated Report (violations expected)...")
    flags_dirty = get_compliance_flags(CONTAMINATED_REPORT)
    if flags_dirty:
        print(f"  PASS  Detected {len(flags_dirty)} compliance flag(s):")
        for f in flags_dirty:
            print(f"        - {f}")
        print()
    else:
        print(f"  FAIL  No flags detected — pattern matching may be broken.\n")
        sys.exit(1)

    # -- Test 3: Strict mode output -------------------------------------------
    print("[TEST 3] Strict Mode Sanitization...")
    strict_output = sanitize_and_append_disclaimer(CONTAMINATED_REPORT, strict_mode=True)
    if "COMPLIANCE ALERT" in strict_output:
        print("  PASS  Compliance alert header present in strict mode output.")
    else:
        print("  FAIL  Compliance alert header missing from strict mode output.")
    if "Regulatory Disclaimer" in strict_output:
        print("  PASS  Regulatory disclaimer appended.\n")
    else:
        print("  FAIL  Disclaimer missing from output.\n")
        sys.exit(1)

    # -- Test 4: Non-strict mode (clean report) --------------------------------
    print("[TEST 4] Non-Strict Mode (clean report)...")
    clean_output = sanitize_and_append_disclaimer(CLEAN_REPORT, strict_mode=False)
    if "COMPLIANCE ALERT" not in clean_output and "Regulatory Disclaimer" in clean_output:
        print("  PASS  No alert header; disclaimer appended correctly.\n")
    else:
        print("  FAIL  Unexpected output structure.\n")

    # -- Test 5: Edge case — empty input ----------------------------------------
    print("[TEST 5] Edge Case — Empty Input...")
    empty_output = sanitize_and_append_disclaimer("")
    if "Regulatory Disclaimer" in empty_output:
        print("  PASS  Empty input handled gracefully; disclaimer returned.\n")
    else:
        print("  FAIL  Empty input not handled.\n")

    # -- Summary ---------------------------------------------------------------
    print("-" * 70)
    print("  FULL SANITIZED CLEAN REPORT PREVIEW:")
    print("-" * 70)
    clean_preview = sanitize_and_append_disclaimer(CLEAN_REPORT)
    print(clean_preview[:600] + "...")
    print("-" * 70)

    print("\n" + "=" * 70)
    print("  guardrails.py self-test complete.")
    print("=" * 70 + "\n")
